@localUrl = http://127.0.0.1:8000/api/v1
@liveUrl = https://insights.alwaysdata.net/api/v1
@bearer=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzI3NDYzNDUyLCJleHAiOjE3Mjc0NjcwNTIsIm5iZiI6MTcyNzQ2MzQ1MiwianRpIjoialVHWTdKbG91RE9kcHN2WCIsInN1YiI6IjEiLCJwcnYiOiJiOTEyNzk5NzhmMTFhYTdiYzU2NzA0ODdmZmYwMWUyMjgyNTNmZTQ4In0.FShnNe31KH_3-UFH04Xy7EtGvTTSWl6Hhg17w2JvY2I

### Register
POST {{liveUrl}}/admin/user
Accept: application/json
Content-Type: application/json
Authorization: {{bearer}}

{
    "email": "golden.f2002@gmail.com",
    "password": "12345678",
    "password_confirmation": "12345678",
    "first_name": "Golden",
    "last_name": "Eke",
    "isAdmin": false
}

### Login
POST {{localUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "favour.e2002@gmail.com",
    "password": "12345678"
}

### Register
GET {{localUrl}}/admin/user
Accept: application/json
Content-Type: application/json
Authorization: {{bearer}}

###
GET {{localUrl}}/shipment?status=Approved
Accept: application/json
Content-Type: application/json
Authorization: {{bearer}}

# {
#     "status": "Approved"
# }
