@localUrl = http://127.0.0.1:8000/api/v1
@liveUrl = https://insights.alwaysdata.net/api/v1
@bearer=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2luc2lnaHRzLmFsd2F5c2RhdGEubmV0L2FwaS92MS9sb2dpbiIsImlhdCI6MTcyNzQ2NDA2MCwiZXhwIjoxNzI3NDY3NjYwLCJuYmYiOjE3Mjc0NjQwNjAsImp0aSI6IkJ5bFRqbFBXNDVVMHJCUmwiLCJzdWIiOiIxIiwicHJ2IjoiYjkxMjc5OTc4ZjExYWE3YmM1NjcwNDg3ZmZmMDFlMjI4MjUzZmU0OCJ9.1TCnwCxnAPUToxuqUQhi4E7vrsox7kraCeVRzuJCCJQ

### Register
POST {{liveUrl}}/admin/user
Accept: application/json
Content-Type: application/json
Authorization: {{bearer}}

{
    "email": "golden.f2002@gmail.com",
    "password": "12345678",
    "password_confirmation": "12345678",
    "first_name": "Golden",
    "last_name": "Eke",
    "isAdmin": false
}

### Login
POST {{liveUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "favour@gmail.com",
    "password": "12345678"
}

### Register
GET {{localUrl}}/admin/user
Accept: application/json
Content-Type: application/json
Authorization: {{bearer}}

###
GET {{liveUrl}}/shipment
Accept: application/json
Content-Type: application/json
Authorization: {{bearer}}

{
    "status": "Pending"
}
